from __future__ import annotations

"""Fixed deck domain vocabulary and action roles for the hierarchical engine."""

from .validated_rule_profile import (
    PLAYER_NAME, DECK,
    DARK, FROSLASS, MUNKIDORI, IMPIDIMP, MORGREM, GRIMMSNARL, SNORUNT,
    RARE_CANDY, UNFAIR_STAMP, POFFIN, NIGHT_STRETCHER, POKEGEAR,
    TOOL_SCRAPPER, POKE_PAD, BOSS, PETREL, LILLIE, DAWN, SPIKEMUTH,
    FILCH, IMPIDIMP_ATTACK, MORGREM_ATTACK, SHADOW_BULLET,
    MAIN, SETUP_ACTIVE, SETUP_BENCH, SWITCH, TO_ACTIVE, TO_BENCH, TO_HAND,
    DISCARD_CTX, DAMAGE_COUNTER, DAMAGE, REMOVE_DAMAGE, ATTACH_FROM, ATTACH_TO,
    DISCARD_TOOL, DISCARD_ENERGY, SKILL_ORDER, EVOLVE_CTX, DRAW_COUNT,
    REMOVE_DAMAGE_COUNT, IS_FIRST, MULLIGAN, ACTIVATE,
)

BUILD_ID = "public_fixed_deck_expert"

ATTACK_LINE = frozenset((IMPIDIMP, MORGREM, GRIMMSNARL))
FROSLASS_LINE = frozenset((SNORUNT, FROSLASS))
DRAW_SUPPORTERS = frozenset((LILLIE, DAWN))
TARGETED_SUPPORTERS = frozenset((PETREL, BOSS))
