#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
merge.py — 将多文件 Agent 合并为单文件 main.py（Kaggle 提交格式）

用法：
    python3 merge.py              # 生成 main.py
    bash pack.sh                  # 打包 submission.tar.gz
"""

import os
import re

# 模块依赖顺序（被依赖的在前）
MODULE_ORDER = [
    "card_meta.py",
    "option_scorer.py",
    "state_parser.py",
    "decision_gate.py",
    "handlers.py",
    "main_entry.py",
]

# 标准库模块白名单
STDLIB_MODULES = {
    "dataclasses", "typing", "enum", "json", "os", "random",
    "hashlib", "csv", "collections", "abc", "inspect", "functools",
}


def is_stdlib_import(line: str) -> bool:
    """判断 import 语句是否来自标准库"""
    line = line.strip()
    if not (line.startswith("import ") or line.startswith("from ")):
        return False

    if line.startswith("import "):
        module = line.split()[1].split(".")[0].split("as")[0].strip()
    else:  # from x import y
        module = line.split()[1].split(".")[0].strip()

    return module in STDLIB_MODULES


def extract_content(filepath: str) -> tuple:
    """提取文件的 import 语句和代码内容"""
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()

    lines = content.split("\n")
    imports = []
    code_lines = []

    for line in lines:
        stripped = line.strip()
        if stripped.startswith("import ") or stripped.startswith("from "):
            if is_stdlib_import(stripped):
                imports.append(stripped)
            # 项目内 import 直接跳过
            continue
        else:
            code_lines.append(line)

    return imports, "\n".join(code_lines)


def merge(output_path: str = "main.py"):
    """合并所有模块为单文件"""
    all_imports = set()
    code_blocks = []

    for module in MODULE_ORDER:
        if not os.path.exists(module):
            print(f"⚠️  跳过缺失文件: {module}")
            continue

        imports, code = extract_content(module)
        all_imports.update(imports)
        code_blocks.append(
            f"\n# {'=' * 60}\n"
            f"# Module: {module}\n"
            f"# {'=' * 60}\n\n"
            f"{code}"
        )
        print(f"  ✓ 合并: {module}")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("# -*- coding: utf-8 -*-\n")
        f.write(
            '''"""\n"
            "PTCG Battle Agent — Merged for Kaggle Submission\n"
            "Generated by merge.py\n"
            """\n'''
        )
        f.write("\n")

        # 标准库 imports（去重排序）
        for imp in sorted(all_imports):
            f.write(imp + "\n")
        f.write("\n")

        # 各模块代码
        for block in code_blocks:
            f.write(block + "\n")

    # 统计
    total_lines = sum(1 for _ in open(output_path, "r", encoding="utf-8"))
    print(f"\n✅ 合并完成: {output_path} ({total_lines} 行)")
    print(f"   包含 {len(MODULE_ORDER)} 个模块")


if __name__ == "__main__":
    merge()
